version: '3'
services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/code:/var/www/html
  redis:
    image: "redis:alpine"
  postgresql:
    image: "postgres:10"
    ports:
      - "5432:5432"
    env_file: ./postgres.env
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
    volumes:
      - ./postgres-volume:/var/lib/postgresql
  keycloak:
    image: "jboss/keycloak:latest"
    ports:
      - "8888:8080"
      - "8443:8443"
    env_file:
      - ./keycloak.env
    environment:
      - DB_VENDOR=postgres
      - KEYCLOAK_USER=admin
      - POSTGRES_ADDR=postgresql
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
